import React from "react";

interface RationaleSourceBadgeProps {
  source: "groq" | "claude" | "mock" | string;
}

export const RationaleSourceBadge: React.FC<RationaleSourceBadgeProps> = ({ source }) => {
  const normalized = (source || "mock").toLowerCase();

  let badgeClass = "badge-source-mock";
  let displayLabel = "SRC: MOCK";

  if (normalized === "groq") {
    badgeClass = "badge-source-groq";
    displayLabel = "SRC: GROQ (LLAMA-3.1-8B)";
  } else if (normalized === "claude") {
    badgeClass = "badge-source-claude";
    displayLabel = "SRC: CLAUDE";
  }

  return (
    <span
      className={`badge ${badgeClass}`}
      title={`Rationale generated by: ${normalized.toUpperCase()}`}
      style={{ fontSize: "10px", padding: "1px 5px" }}
    >
      {displayLabel}
    </span>
  );
};
